[package]
name = "proj1_acoustic_link"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = "3.5.0"
jack = "0.11.4"
once_cell = "1.18.0"
rand = "0.8.5"
reed-solomon = "0.2.1"
rustfft = "6.1.0"
slice-deque = "0.3.0"

[dependencies.reed-solomon-erasure]
version = "6.0.0"
features = ["simd-accel"]
