[package]
name = "proj1_acoustic_link"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = "3.5.0"
jack = "0.11.4"

[profile.release]
lto = true
opt-level = 3
strip = "symbols"
codegen-units = 1
